site_name: ApiX CLI
site_url: https://apik.cloud/
nav:
  - Home: index.md
  - Project: project.md
  - Projects: projects.md
  - Images: images.md
  - Congifuration: config.md

markdown_extensions:
    - mkdocs-click
theme: readthedocs
